[project]
name = "dependency-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.scripts]
depguy = "dependency_agent.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
